USE prova_funcionarios;

CREATE TABLE Setor (
ID_SETOR INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOME VARCHAR(30)
);

CREATE TABLE Funcionario (
ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOME VARCHAR(50),
FK_SETOR INT,
NU_SALARIO DOUBLE,
DS_EMAIL VARCHAR(50),
NU_IDADE INT,
FOREIGN KEY (FK_SETOR) REFERENCES Setor(ID_SETOR)
);
